/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.animalshelter;

import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.cfg.Configuration;

import com.animalshelter.entity.Animal;

public class App {
	public String getGreeting() {
		return "Hello World!";
	}

	public static void main(String[] args) {
		System.out.println(new App().getGreeting());
		
		//Creating a new entity
		Animal animal = new Animal();
		animal.setaHeight(11);
		animal.setaWeight(30);
		animal.setaName("Scooby");
		animal.setaType("Dog");
		animal.setaId(0);
		
		//Saving using session.save
		Configuration config = new Configuration().configure().addAnnotatedClass(Animal.class);
        SessionFactory sf = config.buildSessionFactory();
        Session session = sf.openSession();
        Transaction tx = session.beginTransaction();
        session.save(animal);
        //employee = session.get(Employee.class, 0);
        tx.commit();
        
        
        //Fetching using session.get
        Animal fetchedAnimal = session.get(Animal.class, 1);
        System.out.println(fetchedAnimal);
        
        
        //Removing using session.remove
        //Make sure that an animal with aid = 0 exists
        tx = session.beginTransaction();
        session.remove(session.get(Animal.class, 0));
        tx.commit();
		
	}
}
