/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.animalshelter;

import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.cfg.Configuration;

import com.animalshelter.entity.Animal;

public class App {
	public String getGreeting() {
		return "Hello World!";
	}

	public static void main(String[] args) {
		System.out.println(new App().getGreeting());

		// Creating a new entity
		Animal animal = new Animal();
		animal.setaHeight(11);
		// animal.setaWeight(30);
		animal.setaName("Scooby");
		animal.setaType("Dog");
		animal.setaId(0);

		// Saving using session.save
		Configuration config = new Configuration().configure().addAnnotatedClass(Animal.class);
		SessionFactory sf = config.buildSessionFactory();
		Session session = sf.openSession();
		Transaction tx = session.beginTransaction();
		session.save(animal);
		// employee = session.get(Employee.class, 0);
		tx.commit();
		session.close();
		// Fetching using session.get
		// Automatic First level cache in the same session
		Session session1 = sf.openSession();
		Animal fetchedAnimal = session1.get(Animal.class, 1);
		Animal fetchedAnimal2 = session1.get(Animal.class, 1);
		System.out.println(fetchedAnimal);
		System.out.println(fetchedAnimal2);
		session.close();

		// Making sure the same select query wont be asking from the database again
		// because
		// we have implemented second level cache using ehcache
		Session session2 = sf.openSession();
		Animal fetchedAnimal3 = session2.get(Animal.class, 1);
		System.out.println(fetchedAnimal3);
		// Removing using session.remove
		// Make sure that an animal with aid = 0 exists
		tx = session.beginTransaction();
		session.remove(session.get(Animal.class, 5));
		tx.commit();

	}
}
